// calculate the bonus earned by 10 sales representatives


#include <stdio.h>

int main()
{
    int num_of_rep;
    float total_bonus, bonus, income_generated;

    for (num_of_rep = 1; num_of_rep<=10; num_of_rep = num_of_rep + 1){
        printf("\nEnter income generated: $");
        scanf("%f", & income_generated);

        if (income_generated >= 20000) 
            bonus = income_generated * 0.2;
        else
            bonus = income_generated * 0.05;
        
        printf("\nBonus earned by Sales Rep %d is $%.2f\n",num_of_rep, bonus);

        total_bonus = total_bonus + bonus;
        }
    printf("\nThe total income generated by the Sales Rep is $%.2f", total_bonus);
    
}